version: '3.8'

name: manager-service-container
services:
  app:
    image: 'quarkus/manager-service'
    container_name: "manager-app"
    ports:
      - '8080:8080'
    links:
      - "manager-db"
    environment:
      - DB_USER=root
      - DB_PWD=root
      - DB_URL=jdbc:postgresql://localhost:5432/manager

  manager-db:
    image: postgres:15
    container_name: "manager-db"
    environment:
      - POSTGRES_DB=manager
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - manager:/var/lib/postgresql/data
      - ./../../../db/sql/create_manager_schemas.sql:/docker-entrypoint-initdb.d/create_manager_schemas.sql
volumes:
  manager:
    driver: local